import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "~/src/apps/providers";
import { Toaster } from "~/src/portal/toast-client";
import { Logger } from "~/src/logger/example";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className=" bg-gray-100 min-h-screen flex w-screen justify-center">
            <div className=" bg-white min-w-[420px]">{children}</div>
          </div>
          <Logger />
        </Providers>
        <Toaster />
        <div id="toast" />
        <div id="dialog" />
      </body>
    </html>
  );
}
