import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "~/src/apps/providers";
import { Toaster } from "~/src/@deprecated/portal/toast-client";
import { Logger } from "~/src/@deprecated/logger/example";
import { OverlayProvider } from "./overlay-provider";
import { PORTAL_ID } from "~/src/@deprecated/portal-id";
import "@xionwcfm/token/style";
import "@xionwcfm/xds/style";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <OverlayProvider>
            <div className=" bg-gray-100 min-h-screen flex w-screen justify-center">
              <div className=" bg-white max-w-[420px] w-screen ">
                {children}
                <div id="toast" />
                <div id="dialog" />
              </div>
            </div>
            <Logger />
            <Toaster />
            {Object.values(PORTAL_ID).map((id) => (
              <div id={id} key={id} />
            ))}
          </OverlayProvider>
        </Providers>
      </body>
    </html>
  );
}
